disabled_rules:
    - identifier_name
    - force_cast
    - line_length
    - unused_closure_parameter
    - large_tuple
    - trailing_whitespace
    - function_parameter_count
    - redundant_void_return

line_length:
    warning: 500
    error: 500

